# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  dotnet:
    build:
      context: "C:\\Dima\\ADO\\DotNet\\RabbitMQ"
      dockerfile: "WebAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/WebAPI.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "dotnet:dev"
    ports: []
    volumes:
    - "C:\\Users\\dmitr\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Dima\\ADO\\DotNet\\RabbitMQ\\WebAPI:/app:rw"
    - "C:\\Dima\\ADO\\DotNet\\RabbitMQ:/src:rw"
    working_dir: "/app"
  dotnet-consumer:
    build:
      context: "C:\\Dima\\ADO\\DotNet\\RabbitMQ"
      dockerfile: "WebAPI.Consumer/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/WebAPI.Consumer.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "dotnet-consumer:dev"
    ports: []
    volumes:
    - "C:\\Users\\dmitr\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Dima\\ADO\\DotNet\\RabbitMQ\\WebAPI.Consumer:/app:rw"
    - "C:\\Dima\\ADO\\DotNet\\RabbitMQ:/src:rw"
    working_dir: "/app"
